apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "educacionit-app.fullname" . }}
  labels:
    {{- include "educacionit-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "educacionit-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "educacionit-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "educacionit-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}
            - name: DB_PASS
              value: {{ .Values.env.DB_PASS | quote }}
            - name: DB_URI
              value: {{ .Values.env.DB_URI | quote }}
            - name: DB_USER
              value: {{ .Values.env.DB_USER | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
