apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "educacionit-app.fullname" . }}
  labels:
    {{- include "educacionit-app.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: "Helm"
