apiVersion: v1
kind: Service
metadata:
  name: {{ include "educacionit-app.fullname" . }}
  labels:
    {{- include "educacionit-app.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "educacionit-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
