{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- if .Values.serviceAccount.name -}}
    {{ .Values.serviceAccount.name }}
  {{- else -}}
    {{ include "educacionit-app.fullname" . }}
  {{- end }}
  labels:
    {{- include "educacionit-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/managed-by: "Helm"
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
